# Jekyll設定ファイル for GitHub Pages
theme: jekyll-theme-cayman
title: AutoSlideIdea
description: Markdownベースのシンプルなプレゼンテーション作成ツール
lang: ja

# ナビゲーション
github:
  repository_url: https://github.com/dobachi/AutoSlideIdea

# プラグイン（GitHub Pages標準）
plugins:
  - jekyll-relative-links
  - jekyll-sitemap

# Markdown設定
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 除外ファイル
exclude:
  - "*.log"
  - "GITHUB_PAGES_PLAN.md"
  - "SIMPLE_GITHUB_PAGES_PLAN.md"